@startuml
title Communication Diagram - Process Payment

' Aceasta diagrama arata colaborarea dintre obiecte pentru 
' realizarea platii folosind Student Credit.

allowmixing
skinparam nodesep 60
skinparam ranksep 60

object "ui: UI/Handler" as UI
object "orderService: OrderService" as OrderSvc
object "order: Order" as Order
object "user: CampusUser" as CampusUser
object "credit: StudentCredit" as StudentCredit
object "payment: Payment" as Payment

UI -right-> OrderSvc : 1: pay(order, method, user)\n1.7: return Payment
OrderSvc -down-> Order : 1.1: getTotal()\n1.5: setPayment(payment)\n1.6: setStatus(PAID)
OrderSvc -right-> CampusUser : 1.2: getStudentCredit()
CampusUser -down-> StudentCredit : 1.2.1: getBudget()
OrderSvc ..> StudentCredit : 1.3: setBudget(budget - total)
OrderSvc -up-> Payment : 1.4: <<create>>(success=true)

@enduml
